spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   
    
     
  datasource:
    url: jdbc:mysql://localhost:3306/netcunddb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
